// Code generated by 'yaegi extract github.com/nfnt/resize'. DO NOT EDIT.

package symbols

import (
	"github.com/nfnt/resize"
	"reflect"
)

func init() {
	Symbols["github.com/nfnt/resize/resize"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bicubic":           reflect.ValueOf(resize.Bicubic),
		"Bilinear":          reflect.ValueOf(resize.Bilinear),
		"Lanczos2":          reflect.ValueOf(resize.Lanczos2),
		"Lanczos3":          reflect.ValueOf(resize.Lanczos3),
		"MitchellNetravali": reflect.ValueOf(resize.MitchellNetravali),
		"NearestNeighbor":   reflect.ValueOf(resize.NearestNeighbor),
		"Resize":            reflect.ValueOf(resize.Resize),
		"Thumbnail":         reflect.ValueOf(resize.Thumbnail),

		// type definitions
		"InterpolationFunction": reflect.ValueOf((*resize.InterpolationFunction)(nil)),
	}
}
