// Code generated by 'yaegi extract github.com/XiaoMengXinX/CloudMusicDownloader/downloader'. DO NOT EDIT.

package symbols

import (
	"github.com/XiaoMengXinX/CloudMusicDownloader/downloader"
	"reflect"
)

func init() {
	Symbols["github.com/XiaoMengXinX/CloudMusicDownloader/downloader/downloader"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddFlacId3v2":  reflect.ValueOf(downloader.AddFlacId3v2),
		"AddMp3Id3v2":   reflect.ValueOf(downloader.AddMp3Id3v2),
		"CreateMarker":  reflect.ValueOf(downloader.CreateMarker),
		"Decrypt163key": reflect.ValueOf(downloader.Decrypt163key),
		"ParseArtist":   reflect.ValueOf(downloader.ParseArtist),
		"ReadFlacKey":   reflect.ValueOf(downloader.ReadFlacKey),
		"ReadMp3Key":    reflect.ValueOf(downloader.ReadMp3Key),

		// type definitions
		"MarkerData": reflect.ValueOf((*downloader.MarkerData)(nil)),
	}
}
