// Code generated by 'yaegi extract github.com/XiaoMengXinX/Music163Api-Go/types'. DO NOT EDIT.

package symbols

import (
	"github.com/XiaoMengXinX/Music163Api-Go/types"
	"reflect"
)

func init() {
	Symbols["github.com/XiaoMengXinX/Music163Api-Go/types/types"] = map[string]reflect.Value{
		// type definitions
		"AddCommentData":           reflect.ValueOf((*types.AddCommentData)(nil)),
		"BatchCloudbeanNumData":    reflect.ValueOf((*types.BatchCloudbeanNumData)(nil)),
		"BatchLoginStatusData":     reflect.ValueOf((*types.BatchLoginStatusData)(nil)),
		"BatchMusicianSignData":    reflect.ValueOf((*types.BatchMusicianSignData)(nil)),
		"BatchMusicianTasksData":   reflect.ValueOf((*types.BatchMusicianTasksData)(nil)),
		"BatchObtainCLoudbeanData": reflect.ValueOf((*types.BatchObtainCLoudbeanData)(nil)),
		"BatchSongDetailData":      reflect.ValueOf((*types.BatchSongDetailData)(nil)),
		"BatchSongURLData":         reflect.ValueOf((*types.BatchSongURLData)(nil)),
		"BatchUserDetailData":      reflect.ValueOf((*types.BatchUserDetailData)(nil)),
		"BatchUserInfoData":        reflect.ValueOf((*types.BatchUserInfoData)(nil)),
		"BatchUserSettingData":     reflect.ValueOf((*types.BatchUserSettingData)(nil)),
		"BatchUserSignData":        reflect.ValueOf((*types.BatchUserSignData)(nil)),
		"CloudBeanNumData":         reflect.ValueOf((*types.CloudBeanNumData)(nil)),
		"DelCommentData":           reflect.ValueOf((*types.DelCommentData)(nil)),
		"DelEventData":             reflect.ValueOf((*types.DelEventData)(nil)),
		"DelPlaylistData":          reflect.ValueOf((*types.DelPlaylistData)(nil)),
		"GetCommentData":           reflect.ValueOf((*types.GetCommentData)(nil)),
		"LoginStatusData":          reflect.ValueOf((*types.LoginStatusData)(nil)),
		"MusicianSignData":         reflect.ValueOf((*types.MusicianSignData)(nil)),
		"MusicianTasksData":        reflect.ValueOf((*types.MusicianTasksData)(nil)),
		"NewPlaylistData":          reflect.ValueOf((*types.NewPlaylistData)(nil)),
		"NosTokenData":             reflect.ValueOf((*types.NosTokenData)(nil)),
		"ObtainCloudebeanData":     reflect.ValueOf((*types.ObtainCloudebeanData)(nil)),
		"PlaylistDetailData":       reflect.ValueOf((*types.PlaylistDetailData)(nil)),
		"PlaylistTracksData":       reflect.ValueOf((*types.PlaylistTracksData)(nil)),
		"QrCheckData":              reflect.ValueOf((*types.QrCheckData)(nil)),
		"QrUnikeyData":             reflect.ValueOf((*types.QrUnikeyData)(nil)),
		"RecommendSongsData":       reflect.ValueOf((*types.RecommendSongsData)(nil)),
		"ReplyCommentData":         reflect.ValueOf((*types.ReplyCommentData)(nil)),
		"SearchComplexData":        reflect.ValueOf((*types.SearchComplexData)(nil)),
		"SearchMultiMatchData":     reflect.ValueOf((*types.SearchMultiMatchData)(nil)),
		"SearchSongData":           reflect.ValueOf((*types.SearchSongData)(nil)),
		"SearchSuggestData":        reflect.ValueOf((*types.SearchSuggestData)(nil)),
		"SendEventData":            reflect.ValueOf((*types.SendEventData)(nil)),
		"SendMlogData":             reflect.ValueOf((*types.SendMlogData)(nil)),
		"SendMsgData":              reflect.ValueOf((*types.SendMsgData)(nil)),
		"ShortURLData":             reflect.ValueOf((*types.ShortURLData)(nil)),
		"SongDetailData":           reflect.ValueOf((*types.SongDetailData)(nil)),
		"SongDownloadURLData":      reflect.ValueOf((*types.SongDownloadURLData)(nil)),
		"SongLikeData":             reflect.ValueOf((*types.SongLikeData)(nil)),
		"SongLyricData":            reflect.ValueOf((*types.SongLyricData)(nil)),
		"SongURLData":              reflect.ValueOf((*types.SongURLData)(nil)),
		"SongsDetailData":          reflect.ValueOf((*types.SongsDetailData)(nil)),
		"SongsURLData":             reflect.ValueOf((*types.SongsURLData)(nil)),
		"UploadEventImgData":       reflect.ValueOf((*types.UploadEventImgData)(nil)),
		"UploadFileData":           reflect.ValueOf((*types.UploadFileData)(nil)),
		"UploadNodeData":           reflect.ValueOf((*types.UploadNodeData)(nil)),
		"UserDetailData":           reflect.ValueOf((*types.UserDetailData)(nil)),
		"UserInfoData":             reflect.ValueOf((*types.UserInfoData)(nil)),
		"UserPlaylistData":         reflect.ValueOf((*types.UserPlaylistData)(nil)),
		"UserSettingData":          reflect.ValueOf((*types.UserSettingData)(nil)),
		"UserSignData":             reflect.ValueOf((*types.UserSignData)(nil)),
		"VipGrowthpointData":       reflect.ValueOf((*types.VipGrowthpointData)(nil)),
		"VipInfoData":              reflect.ValueOf((*types.VipInfoData)(nil)),
		"VipTaskRewardData":        reflect.ValueOf((*types.VipTaskRewardData)(nil)),
		"VipTaskslistDetailData":   reflect.ValueOf((*types.VipTaskslistDetailData)(nil)),
	}
}
