// Code generated by 'yaegi extract github.com/go-telegram-bot-api/telegram-bot-api/v5'. DO NOT EDIT.

package symbols

import (
	"github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"go/constant"
	"go/token"
	"io"
	"net/http"
	"reflect"
)

func init() {
	Symbols["github.com/go-telegram-bot-api/telegram-bot-api/v5/tgbotapi"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"APIEndpoint":              reflect.ValueOf(constant.MakeFromLiteral("\"https://api.telegram.org/bot%s/%s\"", token.STRING, 0)),
		"ChatChooseSticker":        reflect.ValueOf(constant.MakeFromLiteral("\"choose_sticker\"", token.STRING, 0)),
		"ChatFindLocation":         reflect.ValueOf(constant.MakeFromLiteral("\"find_location\"", token.STRING, 0)),
		"ChatRecordVideo":          reflect.ValueOf(constant.MakeFromLiteral("\"record_video\"", token.STRING, 0)),
		"ChatRecordVideoNote":      reflect.ValueOf(constant.MakeFromLiteral("\"record_video_note\"", token.STRING, 0)),
		"ChatRecordVoice":          reflect.ValueOf(constant.MakeFromLiteral("\"record_voice\"", token.STRING, 0)),
		"ChatTyping":               reflect.ValueOf(constant.MakeFromLiteral("\"typing\"", token.STRING, 0)),
		"ChatUploadDocument":       reflect.ValueOf(constant.MakeFromLiteral("\"upload_document\"", token.STRING, 0)),
		"ChatUploadPhoto":          reflect.ValueOf(constant.MakeFromLiteral("\"upload_photo\"", token.STRING, 0)),
		"ChatUploadVideo":          reflect.ValueOf(constant.MakeFromLiteral("\"upload_video\"", token.STRING, 0)),
		"ChatUploadVideoNote":      reflect.ValueOf(constant.MakeFromLiteral("\"upload_video_note\"", token.STRING, 0)),
		"ChatUploadVoice":          reflect.ValueOf(constant.MakeFromLiteral("\"upload_voice\"", token.STRING, 0)),
		"ErrAPIForbidden":          reflect.ValueOf(constant.MakeFromLiteral("\"forbidden\"", token.STRING, 0)),
		"ErrBadURL":                reflect.ValueOf(constant.MakeFromLiteral("\"bad or empty url\"", token.STRING, 0)),
		"EscapeText":               reflect.ValueOf(tgbotapi.EscapeText),
		"FileEndpoint":             reflect.ValueOf(constant.MakeFromLiteral("\"https://api.telegram.org/file/bot%s/%s\"", token.STRING, 0)),
		"ModeHTML":                 reflect.ValueOf(constant.MakeFromLiteral("\"HTML\"", token.STRING, 0)),
		"ModeMarkdown":             reflect.ValueOf(constant.MakeFromLiteral("\"Markdown\"", token.STRING, 0)),
		"ModeMarkdownV2":           reflect.ValueOf(constant.MakeFromLiteral("\"MarkdownV2\"", token.STRING, 0)),
		"NewAnimation":             reflect.ValueOf(tgbotapi.NewAnimation),
		"NewAudio":                 reflect.ValueOf(tgbotapi.NewAudio),
		"NewBotAPI":                reflect.ValueOf(tgbotapi.NewBotAPI),
		"NewBotAPIWithAPIEndpoint": reflect.ValueOf(tgbotapi.NewBotAPIWithAPIEndpoint),
		"NewBotAPIWithClient":      reflect.ValueOf(tgbotapi.NewBotAPIWithClient),
		"NewBotCommandScopeAllChatAdministrators": reflect.ValueOf(tgbotapi.NewBotCommandScopeAllChatAdministrators),
		"NewBotCommandScopeAllGroupChats":         reflect.ValueOf(tgbotapi.NewBotCommandScopeAllGroupChats),
		"NewBotCommandScopeAllPrivateChats":       reflect.ValueOf(tgbotapi.NewBotCommandScopeAllPrivateChats),
		"NewBotCommandScopeChat":                  reflect.ValueOf(tgbotapi.NewBotCommandScopeChat),
		"NewBotCommandScopeChatAdministrators":    reflect.ValueOf(tgbotapi.NewBotCommandScopeChatAdministrators),
		"NewBotCommandScopeChatMember":            reflect.ValueOf(tgbotapi.NewBotCommandScopeChatMember),
		"NewBotCommandScopeDefault":               reflect.ValueOf(tgbotapi.NewBotCommandScopeDefault),
		"NewCallback":                             reflect.ValueOf(tgbotapi.NewCallback),
		"NewCallbackWithAlert":                    reflect.ValueOf(tgbotapi.NewCallbackWithAlert),
		"NewChatAction":                           reflect.ValueOf(tgbotapi.NewChatAction),
		"NewChatDescription":                      reflect.ValueOf(tgbotapi.NewChatDescription),
		"NewChatPhoto":                            reflect.ValueOf(tgbotapi.NewChatPhoto),
		"NewChatTitle":                            reflect.ValueOf(tgbotapi.NewChatTitle),
		"NewContact":                              reflect.ValueOf(tgbotapi.NewContact),
		"NewCopyMessage":                          reflect.ValueOf(tgbotapi.NewCopyMessage),
		"NewDeleteChatPhoto":                      reflect.ValueOf(tgbotapi.NewDeleteChatPhoto),
		"NewDeleteMessage":                        reflect.ValueOf(tgbotapi.NewDeleteMessage),
		"NewDeleteMyCommands":                     reflect.ValueOf(tgbotapi.NewDeleteMyCommands),
		"NewDeleteMyCommandsWithScope":            reflect.ValueOf(tgbotapi.NewDeleteMyCommandsWithScope),
		"NewDeleteMyCommandsWithScopeAndLanguage": reflect.ValueOf(tgbotapi.NewDeleteMyCommandsWithScopeAndLanguage),
		"NewDice":                                 reflect.ValueOf(tgbotapi.NewDice),
		"NewDiceWithEmoji":                        reflect.ValueOf(tgbotapi.NewDiceWithEmoji),
		"NewDocument":                             reflect.ValueOf(tgbotapi.NewDocument),
		"NewEditMessageCaption":                   reflect.ValueOf(tgbotapi.NewEditMessageCaption),
		"NewEditMessageReplyMarkup":               reflect.ValueOf(tgbotapi.NewEditMessageReplyMarkup),
		"NewEditMessageText":                      reflect.ValueOf(tgbotapi.NewEditMessageText),
		"NewEditMessageTextAndMarkup":             reflect.ValueOf(tgbotapi.NewEditMessageTextAndMarkup),
		"NewForward":                              reflect.ValueOf(tgbotapi.NewForward),
		"NewGetMyCommandsWithScope":               reflect.ValueOf(tgbotapi.NewGetMyCommandsWithScope),
		"NewGetMyCommandsWithScopeAndLanguage":    reflect.ValueOf(tgbotapi.NewGetMyCommandsWithScopeAndLanguage),
		"NewInlineKeyboardButtonData":             reflect.ValueOf(tgbotapi.NewInlineKeyboardButtonData),
		"NewInlineKeyboardButtonLoginURL":         reflect.ValueOf(tgbotapi.NewInlineKeyboardButtonLoginURL),
		"NewInlineKeyboardButtonSwitch":           reflect.ValueOf(tgbotapi.NewInlineKeyboardButtonSwitch),
		"NewInlineKeyboardButtonURL":              reflect.ValueOf(tgbotapi.NewInlineKeyboardButtonURL),
		"NewInlineKeyboardMarkup":                 reflect.ValueOf(tgbotapi.NewInlineKeyboardMarkup),
		"NewInlineKeyboardRow":                    reflect.ValueOf(tgbotapi.NewInlineKeyboardRow),
		"NewInlineQueryResultArticle":             reflect.ValueOf(tgbotapi.NewInlineQueryResultArticle),
		"NewInlineQueryResultArticleHTML":         reflect.ValueOf(tgbotapi.NewInlineQueryResultArticleHTML),
		"NewInlineQueryResultArticleMarkdown":     reflect.ValueOf(tgbotapi.NewInlineQueryResultArticleMarkdown),
		"NewInlineQueryResultArticleMarkdownV2":   reflect.ValueOf(tgbotapi.NewInlineQueryResultArticleMarkdownV2),
		"NewInlineQueryResultAudio":               reflect.ValueOf(tgbotapi.NewInlineQueryResultAudio),
		"NewInlineQueryResultCachedAudio":         reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedAudio),
		"NewInlineQueryResultCachedDocument":      reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedDocument),
		"NewInlineQueryResultCachedGIF":           reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedGIF),
		"NewInlineQueryResultCachedMPEG4GIF":      reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedMPEG4GIF),
		"NewInlineQueryResultCachedPhoto":         reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedPhoto),
		"NewInlineQueryResultCachedSticker":       reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedSticker),
		"NewInlineQueryResultCachedVideo":         reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedVideo),
		"NewInlineQueryResultCachedVoice":         reflect.ValueOf(tgbotapi.NewInlineQueryResultCachedVoice),
		"NewInlineQueryResultDocument":            reflect.ValueOf(tgbotapi.NewInlineQueryResultDocument),
		"NewInlineQueryResultGIF":                 reflect.ValueOf(tgbotapi.NewInlineQueryResultGIF),
		"NewInlineQueryResultLocation":            reflect.ValueOf(tgbotapi.NewInlineQueryResultLocation),
		"NewInlineQueryResultMPEG4GIF":            reflect.ValueOf(tgbotapi.NewInlineQueryResultMPEG4GIF),
		"NewInlineQueryResultPhoto":               reflect.ValueOf(tgbotapi.NewInlineQueryResultPhoto),
		"NewInlineQueryResultPhotoWithThumb":      reflect.ValueOf(tgbotapi.NewInlineQueryResultPhotoWithThumb),
		"NewInlineQueryResultVenue":               reflect.ValueOf(tgbotapi.NewInlineQueryResultVenue),
		"NewInlineQueryResultVideo":               reflect.ValueOf(tgbotapi.NewInlineQueryResultVideo),
		"NewInlineQueryResultVoice":               reflect.ValueOf(tgbotapi.NewInlineQueryResultVoice),
		"NewInputMediaAnimation":                  reflect.ValueOf(tgbotapi.NewInputMediaAnimation),
		"NewInputMediaAudio":                      reflect.ValueOf(tgbotapi.NewInputMediaAudio),
		"NewInputMediaDocument":                   reflect.ValueOf(tgbotapi.NewInputMediaDocument),
		"NewInputMediaPhoto":                      reflect.ValueOf(tgbotapi.NewInputMediaPhoto),
		"NewInputMediaVideo":                      reflect.ValueOf(tgbotapi.NewInputMediaVideo),
		"NewInvoice":                              reflect.ValueOf(tgbotapi.NewInvoice),
		"NewKeyboardButton":                       reflect.ValueOf(tgbotapi.NewKeyboardButton),
		"NewKeyboardButtonContact":                reflect.ValueOf(tgbotapi.NewKeyboardButtonContact),
		"NewKeyboardButtonLocation":               reflect.ValueOf(tgbotapi.NewKeyboardButtonLocation),
		"NewKeyboardButtonRow":                    reflect.ValueOf(tgbotapi.NewKeyboardButtonRow),
		"NewLocation":                             reflect.ValueOf(tgbotapi.NewLocation),
		"NewMediaGroup":                           reflect.ValueOf(tgbotapi.NewMediaGroup),
		"NewMessage":                              reflect.ValueOf(tgbotapi.NewMessage),
		"NewMessageToChannel":                     reflect.ValueOf(tgbotapi.NewMessageToChannel),
		"NewOneTimeReplyKeyboard":                 reflect.ValueOf(tgbotapi.NewOneTimeReplyKeyboard),
		"NewPhoto":                                reflect.ValueOf(tgbotapi.NewPhoto),
		"NewPhotoToChannel":                       reflect.ValueOf(tgbotapi.NewPhotoToChannel),
		"NewPoll":                                 reflect.ValueOf(tgbotapi.NewPoll),
		"NewRemoveKeyboard":                       reflect.ValueOf(tgbotapi.NewRemoveKeyboard),
		"NewReplyKeyboard":                        reflect.ValueOf(tgbotapi.NewReplyKeyboard),
		"NewSetMyCommands":                        reflect.ValueOf(tgbotapi.NewSetMyCommands),
		"NewSetMyCommandsWithScope":               reflect.ValueOf(tgbotapi.NewSetMyCommandsWithScope),
		"NewSetMyCommandsWithScopeAndLanguage":    reflect.ValueOf(tgbotapi.NewSetMyCommandsWithScopeAndLanguage),
		"NewSticker":                              reflect.ValueOf(tgbotapi.NewSticker),
		"NewStopPoll":                             reflect.ValueOf(tgbotapi.NewStopPoll),
		"NewUpdate":                               reflect.ValueOf(tgbotapi.NewUpdate),
		"NewUserProfilePhotos":                    reflect.ValueOf(tgbotapi.NewUserProfilePhotos),
		"NewVenue":                                reflect.ValueOf(tgbotapi.NewVenue),
		"NewVideo":                                reflect.ValueOf(tgbotapi.NewVideo),
		"NewVideoNote":                            reflect.ValueOf(tgbotapi.NewVideoNote),
		"NewVoice":                                reflect.ValueOf(tgbotapi.NewVoice),
		"NewWebhook":                              reflect.ValueOf(tgbotapi.NewWebhook),
		"NewWebhookWithCert":                      reflect.ValueOf(tgbotapi.NewWebhookWithCert),
		"SetLogger":                               reflect.ValueOf(tgbotapi.SetLogger),
		"UpdateTypeCallbackQuery":                 reflect.ValueOf(constant.MakeFromLiteral("\"callback_query\"", token.STRING, 0)),
		"UpdateTypeChannelPost":                   reflect.ValueOf(constant.MakeFromLiteral("\"channel_post\"", token.STRING, 0)),
		"UpdateTypeChatMember":                    reflect.ValueOf(constant.MakeFromLiteral("\"chat_member\"", token.STRING, 0)),
		"UpdateTypeChosenInlineResult":            reflect.ValueOf(constant.MakeFromLiteral("\"chosen_inline_result\"", token.STRING, 0)),
		"UpdateTypeEditedChannelPost":             reflect.ValueOf(constant.MakeFromLiteral("\"edited_channel_post\"", token.STRING, 0)),
		"UpdateTypeEditedMessage":                 reflect.ValueOf(constant.MakeFromLiteral("\"edited_message\"", token.STRING, 0)),
		"UpdateTypeInlineQuery":                   reflect.ValueOf(constant.MakeFromLiteral("\"inline_query\"", token.STRING, 0)),
		"UpdateTypeMessage":                       reflect.ValueOf(constant.MakeFromLiteral("\"message\"", token.STRING, 0)),
		"UpdateTypeMyChatMember":                  reflect.ValueOf(constant.MakeFromLiteral("\"my_chat_member\"", token.STRING, 0)),
		"UpdateTypePoll":                          reflect.ValueOf(constant.MakeFromLiteral("\"poll\"", token.STRING, 0)),
		"UpdateTypePollAnswer":                    reflect.ValueOf(constant.MakeFromLiteral("\"poll_answer\"", token.STRING, 0)),
		"UpdateTypePreCheckoutQuery":              reflect.ValueOf(constant.MakeFromLiteral("\"pre_checkout_query\"", token.STRING, 0)),
		"UpdateTypeShippingQuery":                 reflect.ValueOf(constant.MakeFromLiteral("\"shipping_query\"", token.STRING, 0)),
		"WriteToHTTPResponse":                     reflect.ValueOf(tgbotapi.WriteToHTTPResponse),

		// type definitions
		"APIResponse":                      reflect.ValueOf((*tgbotapi.APIResponse)(nil)),
		"AddStickerConfig":                 reflect.ValueOf((*tgbotapi.AddStickerConfig)(nil)),
		"Animation":                        reflect.ValueOf((*tgbotapi.Animation)(nil)),
		"AnimationConfig":                  reflect.ValueOf((*tgbotapi.AnimationConfig)(nil)),
		"ApproveChatJoinRequestConfig":     reflect.ValueOf((*tgbotapi.ApproveChatJoinRequestConfig)(nil)),
		"Audio":                            reflect.ValueOf((*tgbotapi.Audio)(nil)),
		"AudioConfig":                      reflect.ValueOf((*tgbotapi.AudioConfig)(nil)),
		"BanChatMemberConfig":              reflect.ValueOf((*tgbotapi.BanChatMemberConfig)(nil)),
		"BanChatSenderChatConfig":          reflect.ValueOf((*tgbotapi.BanChatSenderChatConfig)(nil)),
		"BaseChat":                         reflect.ValueOf((*tgbotapi.BaseChat)(nil)),
		"BaseEdit":                         reflect.ValueOf((*tgbotapi.BaseEdit)(nil)),
		"BaseFile":                         reflect.ValueOf((*tgbotapi.BaseFile)(nil)),
		"BaseInputMedia":                   reflect.ValueOf((*tgbotapi.BaseInputMedia)(nil)),
		"BotAPI":                           reflect.ValueOf((*tgbotapi.BotAPI)(nil)),
		"BotCommand":                       reflect.ValueOf((*tgbotapi.BotCommand)(nil)),
		"BotCommandScope":                  reflect.ValueOf((*tgbotapi.BotCommandScope)(nil)),
		"BotLogger":                        reflect.ValueOf((*tgbotapi.BotLogger)(nil)),
		"CallbackConfig":                   reflect.ValueOf((*tgbotapi.CallbackConfig)(nil)),
		"CallbackGame":                     reflect.ValueOf((*tgbotapi.CallbackGame)(nil)),
		"CallbackQuery":                    reflect.ValueOf((*tgbotapi.CallbackQuery)(nil)),
		"Chat":                             reflect.ValueOf((*tgbotapi.Chat)(nil)),
		"ChatActionConfig":                 reflect.ValueOf((*tgbotapi.ChatActionConfig)(nil)),
		"ChatAdministratorsConfig":         reflect.ValueOf((*tgbotapi.ChatAdministratorsConfig)(nil)),
		"ChatConfig":                       reflect.ValueOf((*tgbotapi.ChatConfig)(nil)),
		"ChatConfigWithUser":               reflect.ValueOf((*tgbotapi.ChatConfigWithUser)(nil)),
		"ChatInfoConfig":                   reflect.ValueOf((*tgbotapi.ChatInfoConfig)(nil)),
		"ChatInviteLink":                   reflect.ValueOf((*tgbotapi.ChatInviteLink)(nil)),
		"ChatInviteLinkConfig":             reflect.ValueOf((*tgbotapi.ChatInviteLinkConfig)(nil)),
		"ChatJoinRequest":                  reflect.ValueOf((*tgbotapi.ChatJoinRequest)(nil)),
		"ChatLocation":                     reflect.ValueOf((*tgbotapi.ChatLocation)(nil)),
		"ChatMember":                       reflect.ValueOf((*tgbotapi.ChatMember)(nil)),
		"ChatMemberConfig":                 reflect.ValueOf((*tgbotapi.ChatMemberConfig)(nil)),
		"ChatMemberCountConfig":            reflect.ValueOf((*tgbotapi.ChatMemberCountConfig)(nil)),
		"ChatMemberUpdated":                reflect.ValueOf((*tgbotapi.ChatMemberUpdated)(nil)),
		"ChatPermissions":                  reflect.ValueOf((*tgbotapi.ChatPermissions)(nil)),
		"ChatPhoto":                        reflect.ValueOf((*tgbotapi.ChatPhoto)(nil)),
		"Chattable":                        reflect.ValueOf((*tgbotapi.Chattable)(nil)),
		"ChosenInlineResult":               reflect.ValueOf((*tgbotapi.ChosenInlineResult)(nil)),
		"CloseConfig":                      reflect.ValueOf((*tgbotapi.CloseConfig)(nil)),
		"Contact":                          reflect.ValueOf((*tgbotapi.Contact)(nil)),
		"ContactConfig":                    reflect.ValueOf((*tgbotapi.ContactConfig)(nil)),
		"CopyMessageConfig":                reflect.ValueOf((*tgbotapi.CopyMessageConfig)(nil)),
		"CreateChatInviteLinkConfig":       reflect.ValueOf((*tgbotapi.CreateChatInviteLinkConfig)(nil)),
		"Credentials":                      reflect.ValueOf((*tgbotapi.Credentials)(nil)),
		"DataCredentials":                  reflect.ValueOf((*tgbotapi.DataCredentials)(nil)),
		"DeclineChatJoinRequest":           reflect.ValueOf((*tgbotapi.DeclineChatJoinRequest)(nil)),
		"DeleteChatPhotoConfig":            reflect.ValueOf((*tgbotapi.DeleteChatPhotoConfig)(nil)),
		"DeleteChatStickerSetConfig":       reflect.ValueOf((*tgbotapi.DeleteChatStickerSetConfig)(nil)),
		"DeleteMessageConfig":              reflect.ValueOf((*tgbotapi.DeleteMessageConfig)(nil)),
		"DeleteMyCommandsConfig":           reflect.ValueOf((*tgbotapi.DeleteMyCommandsConfig)(nil)),
		"DeleteStickerConfig":              reflect.ValueOf((*tgbotapi.DeleteStickerConfig)(nil)),
		"DeleteWebhookConfig":              reflect.ValueOf((*tgbotapi.DeleteWebhookConfig)(nil)),
		"Dice":                             reflect.ValueOf((*tgbotapi.Dice)(nil)),
		"DiceConfig":                       reflect.ValueOf((*tgbotapi.DiceConfig)(nil)),
		"Document":                         reflect.ValueOf((*tgbotapi.Document)(nil)),
		"DocumentConfig":                   reflect.ValueOf((*tgbotapi.DocumentConfig)(nil)),
		"EditChatInviteLinkConfig":         reflect.ValueOf((*tgbotapi.EditChatInviteLinkConfig)(nil)),
		"EditMessageCaptionConfig":         reflect.ValueOf((*tgbotapi.EditMessageCaptionConfig)(nil)),
		"EditMessageLiveLocationConfig":    reflect.ValueOf((*tgbotapi.EditMessageLiveLocationConfig)(nil)),
		"EditMessageMediaConfig":           reflect.ValueOf((*tgbotapi.EditMessageMediaConfig)(nil)),
		"EditMessageReplyMarkupConfig":     reflect.ValueOf((*tgbotapi.EditMessageReplyMarkupConfig)(nil)),
		"EditMessageTextConfig":            reflect.ValueOf((*tgbotapi.EditMessageTextConfig)(nil)),
		"EncryptedCredentials":             reflect.ValueOf((*tgbotapi.EncryptedCredentials)(nil)),
		"EncryptedPassportElement":         reflect.ValueOf((*tgbotapi.EncryptedPassportElement)(nil)),
		"Error":                            reflect.ValueOf((*tgbotapi.Error)(nil)),
		"File":                             reflect.ValueOf((*tgbotapi.File)(nil)),
		"FileBytes":                        reflect.ValueOf((*tgbotapi.FileBytes)(nil)),
		"FileConfig":                       reflect.ValueOf((*tgbotapi.FileConfig)(nil)),
		"FileCredentials":                  reflect.ValueOf((*tgbotapi.FileCredentials)(nil)),
		"FileID":                           reflect.ValueOf((*tgbotapi.FileID)(nil)),
		"FilePath":                         reflect.ValueOf((*tgbotapi.FilePath)(nil)),
		"FileReader":                       reflect.ValueOf((*tgbotapi.FileReader)(nil)),
		"FileURL":                          reflect.ValueOf((*tgbotapi.FileURL)(nil)),
		"Fileable":                         reflect.ValueOf((*tgbotapi.Fileable)(nil)),
		"ForceReply":                       reflect.ValueOf((*tgbotapi.ForceReply)(nil)),
		"ForwardConfig":                    reflect.ValueOf((*tgbotapi.ForwardConfig)(nil)),
		"Game":                             reflect.ValueOf((*tgbotapi.Game)(nil)),
		"GameConfig":                       reflect.ValueOf((*tgbotapi.GameConfig)(nil)),
		"GameHighScore":                    reflect.ValueOf((*tgbotapi.GameHighScore)(nil)),
		"GetChatMemberConfig":              reflect.ValueOf((*tgbotapi.GetChatMemberConfig)(nil)),
		"GetGameHighScoresConfig":          reflect.ValueOf((*tgbotapi.GetGameHighScoresConfig)(nil)),
		"GetMyCommandsConfig":              reflect.ValueOf((*tgbotapi.GetMyCommandsConfig)(nil)),
		"GetStickerSetConfig":              reflect.ValueOf((*tgbotapi.GetStickerSetConfig)(nil)),
		"HTTPClient":                       reflect.ValueOf((*tgbotapi.HTTPClient)(nil)),
		"IDDocumentData":                   reflect.ValueOf((*tgbotapi.IDDocumentData)(nil)),
		"InlineConfig":                     reflect.ValueOf((*tgbotapi.InlineConfig)(nil)),
		"InlineKeyboardButton":             reflect.ValueOf((*tgbotapi.InlineKeyboardButton)(nil)),
		"InlineKeyboardMarkup":             reflect.ValueOf((*tgbotapi.InlineKeyboardMarkup)(nil)),
		"InlineQuery":                      reflect.ValueOf((*tgbotapi.InlineQuery)(nil)),
		"InlineQueryResultArticle":         reflect.ValueOf((*tgbotapi.InlineQueryResultArticle)(nil)),
		"InlineQueryResultAudio":           reflect.ValueOf((*tgbotapi.InlineQueryResultAudio)(nil)),
		"InlineQueryResultCachedAudio":     reflect.ValueOf((*tgbotapi.InlineQueryResultCachedAudio)(nil)),
		"InlineQueryResultCachedDocument":  reflect.ValueOf((*tgbotapi.InlineQueryResultCachedDocument)(nil)),
		"InlineQueryResultCachedGIF":       reflect.ValueOf((*tgbotapi.InlineQueryResultCachedGIF)(nil)),
		"InlineQueryResultCachedMPEG4GIF":  reflect.ValueOf((*tgbotapi.InlineQueryResultCachedMPEG4GIF)(nil)),
		"InlineQueryResultCachedPhoto":     reflect.ValueOf((*tgbotapi.InlineQueryResultCachedPhoto)(nil)),
		"InlineQueryResultCachedSticker":   reflect.ValueOf((*tgbotapi.InlineQueryResultCachedSticker)(nil)),
		"InlineQueryResultCachedVideo":     reflect.ValueOf((*tgbotapi.InlineQueryResultCachedVideo)(nil)),
		"InlineQueryResultCachedVoice":     reflect.ValueOf((*tgbotapi.InlineQueryResultCachedVoice)(nil)),
		"InlineQueryResultContact":         reflect.ValueOf((*tgbotapi.InlineQueryResultContact)(nil)),
		"InlineQueryResultDocument":        reflect.ValueOf((*tgbotapi.InlineQueryResultDocument)(nil)),
		"InlineQueryResultGIF":             reflect.ValueOf((*tgbotapi.InlineQueryResultGIF)(nil)),
		"InlineQueryResultGame":            reflect.ValueOf((*tgbotapi.InlineQueryResultGame)(nil)),
		"InlineQueryResultLocation":        reflect.ValueOf((*tgbotapi.InlineQueryResultLocation)(nil)),
		"InlineQueryResultMPEG4GIF":        reflect.ValueOf((*tgbotapi.InlineQueryResultMPEG4GIF)(nil)),
		"InlineQueryResultPhoto":           reflect.ValueOf((*tgbotapi.InlineQueryResultPhoto)(nil)),
		"InlineQueryResultVenue":           reflect.ValueOf((*tgbotapi.InlineQueryResultVenue)(nil)),
		"InlineQueryResultVideo":           reflect.ValueOf((*tgbotapi.InlineQueryResultVideo)(nil)),
		"InlineQueryResultVoice":           reflect.ValueOf((*tgbotapi.InlineQueryResultVoice)(nil)),
		"InputContactMessageContent":       reflect.ValueOf((*tgbotapi.InputContactMessageContent)(nil)),
		"InputInvoiceMessageContent":       reflect.ValueOf((*tgbotapi.InputInvoiceMessageContent)(nil)),
		"InputLocationMessageContent":      reflect.ValueOf((*tgbotapi.InputLocationMessageContent)(nil)),
		"InputMediaAnimation":              reflect.ValueOf((*tgbotapi.InputMediaAnimation)(nil)),
		"InputMediaAudio":                  reflect.ValueOf((*tgbotapi.InputMediaAudio)(nil)),
		"InputMediaDocument":               reflect.ValueOf((*tgbotapi.InputMediaDocument)(nil)),
		"InputMediaPhoto":                  reflect.ValueOf((*tgbotapi.InputMediaPhoto)(nil)),
		"InputMediaVideo":                  reflect.ValueOf((*tgbotapi.InputMediaVideo)(nil)),
		"InputTextMessageContent":          reflect.ValueOf((*tgbotapi.InputTextMessageContent)(nil)),
		"InputVenueMessageContent":         reflect.ValueOf((*tgbotapi.InputVenueMessageContent)(nil)),
		"Invoice":                          reflect.ValueOf((*tgbotapi.Invoice)(nil)),
		"InvoiceConfig":                    reflect.ValueOf((*tgbotapi.InvoiceConfig)(nil)),
		"KeyboardButton":                   reflect.ValueOf((*tgbotapi.KeyboardButton)(nil)),
		"KeyboardButtonPollType":           reflect.ValueOf((*tgbotapi.KeyboardButtonPollType)(nil)),
		"KickChatMemberConfig":             reflect.ValueOf((*tgbotapi.KickChatMemberConfig)(nil)),
		"LabeledPrice":                     reflect.ValueOf((*tgbotapi.LabeledPrice)(nil)),
		"LeaveChatConfig":                  reflect.ValueOf((*tgbotapi.LeaveChatConfig)(nil)),
		"Location":                         reflect.ValueOf((*tgbotapi.Location)(nil)),
		"LocationConfig":                   reflect.ValueOf((*tgbotapi.LocationConfig)(nil)),
		"LogOutConfig":                     reflect.ValueOf((*tgbotapi.LogOutConfig)(nil)),
		"LoginURL":                         reflect.ValueOf((*tgbotapi.LoginURL)(nil)),
		"MaskPosition":                     reflect.ValueOf((*tgbotapi.MaskPosition)(nil)),
		"MediaGroupConfig":                 reflect.ValueOf((*tgbotapi.MediaGroupConfig)(nil)),
		"Message":                          reflect.ValueOf((*tgbotapi.Message)(nil)),
		"MessageAutoDeleteTimerChanged":    reflect.ValueOf((*tgbotapi.MessageAutoDeleteTimerChanged)(nil)),
		"MessageConfig":                    reflect.ValueOf((*tgbotapi.MessageConfig)(nil)),
		"MessageEntity":                    reflect.ValueOf((*tgbotapi.MessageEntity)(nil)),
		"MessageID":                        reflect.ValueOf((*tgbotapi.MessageID)(nil)),
		"NewStickerSetConfig":              reflect.ValueOf((*tgbotapi.NewStickerSetConfig)(nil)),
		"OrderInfo":                        reflect.ValueOf((*tgbotapi.OrderInfo)(nil)),
		"Params":                           reflect.ValueOf((*tgbotapi.Params)(nil)),
		"PassportData":                     reflect.ValueOf((*tgbotapi.PassportData)(nil)),
		"PassportElementError":             reflect.ValueOf((*tgbotapi.PassportElementError)(nil)),
		"PassportElementErrorDataField":    reflect.ValueOf((*tgbotapi.PassportElementErrorDataField)(nil)),
		"PassportElementErrorFile":         reflect.ValueOf((*tgbotapi.PassportElementErrorFile)(nil)),
		"PassportElementErrorFiles":        reflect.ValueOf((*tgbotapi.PassportElementErrorFiles)(nil)),
		"PassportElementErrorFrontSide":    reflect.ValueOf((*tgbotapi.PassportElementErrorFrontSide)(nil)),
		"PassportElementErrorReverseSide":  reflect.ValueOf((*tgbotapi.PassportElementErrorReverseSide)(nil)),
		"PassportElementErrorSelfie":       reflect.ValueOf((*tgbotapi.PassportElementErrorSelfie)(nil)),
		"PassportFile":                     reflect.ValueOf((*tgbotapi.PassportFile)(nil)),
		"PassportRequestInfoConfig":        reflect.ValueOf((*tgbotapi.PassportRequestInfoConfig)(nil)),
		"PassportScope":                    reflect.ValueOf((*tgbotapi.PassportScope)(nil)),
		"PassportScopeElement":             reflect.ValueOf((*tgbotapi.PassportScopeElement)(nil)),
		"PassportScopeElementOne":          reflect.ValueOf((*tgbotapi.PassportScopeElementOne)(nil)),
		"PassportScopeElementOneOfSeveral": reflect.ValueOf((*tgbotapi.PassportScopeElementOneOfSeveral)(nil)),
		"PersonalDetails":                  reflect.ValueOf((*tgbotapi.PersonalDetails)(nil)),
		"PhotoConfig":                      reflect.ValueOf((*tgbotapi.PhotoConfig)(nil)),
		"PhotoSize":                        reflect.ValueOf((*tgbotapi.PhotoSize)(nil)),
		"PinChatMessageConfig":             reflect.ValueOf((*tgbotapi.PinChatMessageConfig)(nil)),
		"Poll":                             reflect.ValueOf((*tgbotapi.Poll)(nil)),
		"PollAnswer":                       reflect.ValueOf((*tgbotapi.PollAnswer)(nil)),
		"PollOption":                       reflect.ValueOf((*tgbotapi.PollOption)(nil)),
		"PreCheckoutConfig":                reflect.ValueOf((*tgbotapi.PreCheckoutConfig)(nil)),
		"PreCheckoutQuery":                 reflect.ValueOf((*tgbotapi.PreCheckoutQuery)(nil)),
		"PromoteChatMemberConfig":          reflect.ValueOf((*tgbotapi.PromoteChatMemberConfig)(nil)),
		"ProximityAlertTriggered":          reflect.ValueOf((*tgbotapi.ProximityAlertTriggered)(nil)),
		"ReplyKeyboardMarkup":              reflect.ValueOf((*tgbotapi.ReplyKeyboardMarkup)(nil)),
		"ReplyKeyboardRemove":              reflect.ValueOf((*tgbotapi.ReplyKeyboardRemove)(nil)),
		"RequestFile":                      reflect.ValueOf((*tgbotapi.RequestFile)(nil)),
		"RequestFileData":                  reflect.ValueOf((*tgbotapi.RequestFileData)(nil)),
		"ResponseParameters":               reflect.ValueOf((*tgbotapi.ResponseParameters)(nil)),
		"RestrictChatMemberConfig":         reflect.ValueOf((*tgbotapi.RestrictChatMemberConfig)(nil)),
		"RevokeChatInviteLinkConfig":       reflect.ValueOf((*tgbotapi.RevokeChatInviteLinkConfig)(nil)),
		"SecureData":                       reflect.ValueOf((*tgbotapi.SecureData)(nil)),
		"SecureValue":                      reflect.ValueOf((*tgbotapi.SecureValue)(nil)),
		"SendPollConfig":                   reflect.ValueOf((*tgbotapi.SendPollConfig)(nil)),
		"SetChatAdministratorCustomTitle":  reflect.ValueOf((*tgbotapi.SetChatAdministratorCustomTitle)(nil)),
		"SetChatDescriptionConfig":         reflect.ValueOf((*tgbotapi.SetChatDescriptionConfig)(nil)),
		"SetChatPermissionsConfig":         reflect.ValueOf((*tgbotapi.SetChatPermissionsConfig)(nil)),
		"SetChatPhotoConfig":               reflect.ValueOf((*tgbotapi.SetChatPhotoConfig)(nil)),
		"SetChatStickerSetConfig":          reflect.ValueOf((*tgbotapi.SetChatStickerSetConfig)(nil)),
		"SetChatTitleConfig":               reflect.ValueOf((*tgbotapi.SetChatTitleConfig)(nil)),
		"SetGameScoreConfig":               reflect.ValueOf((*tgbotapi.SetGameScoreConfig)(nil)),
		"SetMyCommandsConfig":              reflect.ValueOf((*tgbotapi.SetMyCommandsConfig)(nil)),
		"SetStickerPositionConfig":         reflect.ValueOf((*tgbotapi.SetStickerPositionConfig)(nil)),
		"SetStickerSetThumbConfig":         reflect.ValueOf((*tgbotapi.SetStickerSetThumbConfig)(nil)),
		"ShippingAddress":                  reflect.ValueOf((*tgbotapi.ShippingAddress)(nil)),
		"ShippingConfig":                   reflect.ValueOf((*tgbotapi.ShippingConfig)(nil)),
		"ShippingOption":                   reflect.ValueOf((*tgbotapi.ShippingOption)(nil)),
		"ShippingQuery":                    reflect.ValueOf((*tgbotapi.ShippingQuery)(nil)),
		"Sticker":                          reflect.ValueOf((*tgbotapi.Sticker)(nil)),
		"StickerConfig":                    reflect.ValueOf((*tgbotapi.StickerConfig)(nil)),
		"StickerSet":                       reflect.ValueOf((*tgbotapi.StickerSet)(nil)),
		"StopMessageLiveLocationConfig":    reflect.ValueOf((*tgbotapi.StopMessageLiveLocationConfig)(nil)),
		"StopPollConfig":                   reflect.ValueOf((*tgbotapi.StopPollConfig)(nil)),
		"SuccessfulPayment":                reflect.ValueOf((*tgbotapi.SuccessfulPayment)(nil)),
		"UnbanChatMemberConfig":            reflect.ValueOf((*tgbotapi.UnbanChatMemberConfig)(nil)),
		"UnbanChatSenderChatConfig":        reflect.ValueOf((*tgbotapi.UnbanChatSenderChatConfig)(nil)),
		"UnpinAllChatMessagesConfig":       reflect.ValueOf((*tgbotapi.UnpinAllChatMessagesConfig)(nil)),
		"UnpinChatMessageConfig":           reflect.ValueOf((*tgbotapi.UnpinChatMessageConfig)(nil)),
		"Update":                           reflect.ValueOf((*tgbotapi.Update)(nil)),
		"UpdateConfig":                     reflect.ValueOf((*tgbotapi.UpdateConfig)(nil)),
		"UpdatesChannel":                   reflect.ValueOf((*tgbotapi.UpdatesChannel)(nil)),
		"UploadStickerConfig":              reflect.ValueOf((*tgbotapi.UploadStickerConfig)(nil)),
		"User":                             reflect.ValueOf((*tgbotapi.User)(nil)),
		"UserProfilePhotos":                reflect.ValueOf((*tgbotapi.UserProfilePhotos)(nil)),
		"UserProfilePhotosConfig":          reflect.ValueOf((*tgbotapi.UserProfilePhotosConfig)(nil)),
		"Venue":                            reflect.ValueOf((*tgbotapi.Venue)(nil)),
		"VenueConfig":                      reflect.ValueOf((*tgbotapi.VenueConfig)(nil)),
		"Video":                            reflect.ValueOf((*tgbotapi.Video)(nil)),
		"VideoConfig":                      reflect.ValueOf((*tgbotapi.VideoConfig)(nil)),
		"VideoNote":                        reflect.ValueOf((*tgbotapi.VideoNote)(nil)),
		"VideoNoteConfig":                  reflect.ValueOf((*tgbotapi.VideoNoteConfig)(nil)),
		"Voice":                            reflect.ValueOf((*tgbotapi.Voice)(nil)),
		"VoiceChatEnded":                   reflect.ValueOf((*tgbotapi.VoiceChatEnded)(nil)),
		"VoiceChatParticipantsInvited":     reflect.ValueOf((*tgbotapi.VoiceChatParticipantsInvited)(nil)),
		"VoiceChatScheduled":               reflect.ValueOf((*tgbotapi.VoiceChatScheduled)(nil)),
		"VoiceChatStarted":                 reflect.ValueOf((*tgbotapi.VoiceChatStarted)(nil)),
		"VoiceConfig":                      reflect.ValueOf((*tgbotapi.VoiceConfig)(nil)),
		"WebhookConfig":                    reflect.ValueOf((*tgbotapi.WebhookConfig)(nil)),
		"WebhookInfo":                      reflect.ValueOf((*tgbotapi.WebhookInfo)(nil)),

		// interface wrapper definitions
		"_BotLogger":            reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_BotLogger)(nil)),
		"_Chattable":            reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_Chattable)(nil)),
		"_Fileable":             reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_Fileable)(nil)),
		"_HTTPClient":           reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_HTTPClient)(nil)),
		"_PassportElementError": reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportElementError)(nil)),
		"_PassportScopeElement": reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportScopeElement)(nil)),
		"_RequestFileData":      reflect.ValueOf((*_github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData)(nil)),
	}
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_BotLogger is an interface wrapper for BotLogger type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_BotLogger struct {
	IValue   interface{}
	WPrintf  func(format string, v ...interface{})
	WPrintln func(v ...interface{})
}

func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_BotLogger) Printf(format string, v ...interface{}) {
	W.WPrintf(format, v...)
}
func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_BotLogger) Println(v ...interface{}) {
	W.WPrintln(v...)
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_Chattable is an interface wrapper for Chattable type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_Chattable struct {
	IValue interface{}
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_Fileable is an interface wrapper for Fileable type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_Fileable struct {
	IValue interface{}
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_HTTPClient is an interface wrapper for HTTPClient type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_HTTPClient struct {
	IValue interface{}
	WDo    func(req *http.Request) (*http.Response, error)
}

func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_HTTPClient) Do(req *http.Request) (*http.Response, error) {
	return W.WDo(req)
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportElementError is an interface wrapper for PassportElementError type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportElementError struct {
	IValue interface{}
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportScopeElement is an interface wrapper for PassportScopeElement type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportScopeElement struct {
	IValue     interface{}
	WScopeType func() string
}

func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_PassportScopeElement) ScopeType() string {
	return W.WScopeType()
}

// _github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData is an interface wrapper for RequestFileData type
type _github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData struct {
	IValue       interface{}
	WNeedsUpload func() bool
	WSendData    func() string
	WUploadData  func() (string, io.Reader, error)
}

func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData) NeedsUpload() bool {
	return W.WNeedsUpload()
}
func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData) SendData() string {
	return W.WSendData()
}
func (W _github_com_go_telegram_bot_api_telegram_bot_api_v5_RequestFileData) UploadData() (string, io.Reader, error) {
	return W.WUploadData()
}
