// Code generated by 'yaegi extract github.com/XiaoMengXinX/Music163bot-Go/v2/util'. DO NOT EDIT.

package symbols

import (
	"github.com/XiaoMengXinX/Music163bot-Go/v2/util"
	"reflect"
)

func init() {
	Symbols["github.com/XiaoMengXinX/Music163bot-Go/v2/util/util"] = map[string]reflect.Value{
		// type definitions
		"SongInfo": reflect.ValueOf((*util.SongInfo)(nil)),
	}
}
